const MS_IN_SEC= 1000,
  SEC_IN_MIN= 60,
  MIN_IN_HR= 60,
  HR_IN_DAY=24

const FORGOT_PASSWORD_TOKEN_TTL = 10*SEC_IN_MIN // 10 mins
const VERIFY_ACCOUNT_TOKEN_TTL = 12*MIN_IN_HR*SEC_IN_MIN // 2 hrs
const SIGNED_IN_TOKEN_TTL = 7*HR_IN_DAY*MIN_IN_HR*SEC_IN_MIN // 7 days
const REMEMBERED_SIGNED_IN_TOKEN_TTL = 12*SIGNED_IN_TOKEN_TTL // 12 weeks
const RESET_PASSWORD_TOKEN_TTL = 10*SEC_IN_MIN // 10 mins

module.exports = {
  FORGOT_PASSWORD_TOKEN_TTL,
  VERIFY_ACCOUNT_TOKEN_TTL,
  SIGNED_IN_TOKEN_TTL,
  REMEMBERED_SIGNED_IN_TOKEN_TTL,
  RESET_PASSWORD_TOKEN_TTL,
  MS_IN_SEC,
  SEC_IN_MIN,
  MIN_IN_HR,
  HR_IN_DAY
}